Meteor.startup(function(){
  if (! ClassesCollection.findOne()) {
    ClassesCollection.insert(
      {"title":"homeroom",
       "time":"first"
      },
    );
    ClassesCollection.insert(
      {"title":"writing",
       "time":"second"
      },
    );
    ClassesCollection.insert(
      {"title":"history",
       "time":"third"
      },
    );
    ClassesCollection.insert(
      {"title":"math",
       "time":"forth"
      },
    );
    if (! StudentsCollection.findOne()) {
      StudentsCollection.insert(
        {"firstName":"john",
         "lastName":"smith"
        },
      );
      StudentsCollection.insert(
        {"firstName":"bob",
         "lastName":"knowsthings"
        },
      );
      StudentsCollection.insert(
        {"firstName":"katie",
         "lastName":"simpson"
        },
      );
      StudentsCollection.insert(
        {"firstName":"dude",
         "lastName":"manguy"
        },
      );
    }
  }
});
